#!/usr/bin/env bash
# Bash port of build-pico-universal-flash-nuke.ps1 for Linux CI/dev machines.
#
# Builds the repo-owned Pico Universal Flash Nuke for RP2040 + RP2350,
# concatenates the UF2s, writes the SHA-256 manifest, and regenerates the
# hash embedded in companion/src/main/pico-universal-flash-nuke-hash.ts —
# the same self-consistency contract as the PowerShell script: the app and
# the UF2 it bundles always come from the same build, because the companion
# refuses to flash a nuke UF2 whose hash differs from the embedded value.
# Run the nuke build BEFORE build:app so the fresh hash gets compiled in.
# Set DS5_BRIDGE_VERIFY_NUKE_HASH=1 to instead fail when the built bytes
# differ from the currently committed hash (toolchain determinism check).
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source_dir="$repo_root/tools/pico-universal-flash-nuke"
build_root="${1:-$repo_root/build/pico-universal-flash-nuke}"
output_path="${2:-$repo_root/companion/firmware/pico-universal-flash-nuke.uf2}"
hash_source_path="$repo_root/companion/src/main/pico-universal-flash-nuke-hash.ts"

cmake -S "$source_dir" -B "$build_root/rp2040" -G Ninja -DPICO_BOARD=pico -DCMAKE_BUILD_TYPE=Release
cmake --build "$build_root/rp2040" --target flash_nuke
cmake -S "$source_dir" -B "$build_root/rp2350" -G Ninja -DPICO_BOARD=pico2 -DCMAKE_BUILD_TYPE=Release
cmake --build "$build_root/rp2350" --target flash_nuke

for uf2 in "$build_root/rp2040/flash_nuke.uf2" "$build_root/rp2350/flash_nuke.uf2"; do
  if [ ! -f "$uf2" ]; then
    echo "Expected UF2 was not produced: $uf2" >&2
    exit 1
  fi
done

mkdir -p "$(dirname "$output_path")"
cat "$build_root/rp2040/flash_nuke.uf2" "$build_root/rp2350/flash_nuke.uf2" > "$output_path"

hash_lower="$(sha256sum "$output_path" | cut -d' ' -f1)"
printf '%s  %s\n' "$hash_lower" "$(basename "$output_path")" > "$output_path.sha256"

if [ "${DS5_BRIDGE_VERIFY_NUKE_HASH:-0}" = "1" ]; then
  embedded="$(grep -oE "[a-f0-9]{64}" "$hash_source_path" | head -1 || true)"
  if [ -z "$embedded" ]; then
    echo "Could not read the embedded nuke hash from $hash_source_path" >&2
    exit 1
  fi
  if [ "$embedded" != "$hash_lower" ]; then
    echo "Built nuke UF2 hash $hash_lower does not match the embedded hash $embedded." >&2
    echo "The toolchain produced different bytes than the committed build." >&2
    exit 1
  fi
else
  {
    echo '// Generated by tools/build-pico-universal-flash-nuke.ps1.'
    echo "export const PICO_UNIVERSAL_FLASH_NUKE_SHA256 = '$hash_lower';"
    echo ''
  } > "$hash_source_path"
  echo "Wrote $hash_source_path"
fi

echo "Built $output_path ($(stat -c%s "$output_path") bytes)"
echo "Wrote $output_path.sha256"
